# Generated by Django 2.0.5 on 2018-05-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180406_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='contest',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
